---
name: CI

on:
    push:
        branches:
            - main
    pull_request:

env:
    FORCE_COLOR: 1

jobs:

    test-package:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.9', '3.12']
                # Test latest and oldest supported package versions
                uv-resolution: [lowest-direct, highest]

        steps:

            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - uses: astral-sh/setup-uv@v7
              with:
                  python-version: ${{ matrix.python-version }}
                  activate-environment: true

            - name: Install package with uv
            # NOTE: We need editable install to collect code coverage
              run: uv pip install --resolution ${{ matrix.uv-resolution }} -e .[dev]

            - name: Run tests without registry tests
              run: pytest -s -m "not registry" tests/

            - name: Install registry extras
              run: uv pip install --resolution ${{ matrix.uv-resolution }} -e .[dev,registry]

            - name: Run all unit tests
              run: pytest -s --cov=aiidalab tests/

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v6
              with:
                  flags: py-${{ matrix.python-version }}
                  token: ${{ secrets.CODECOV_TOKEN }}

    registry-build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:

            - uses: actions/checkout@v6
            - uses: astral-sh/setup-uv@v7
              with:
                  python-version: 3.12
                  activate-environment: true

            - name: Install aiidalab package with registry extras
              run: uv pip install -e .[registry]

            - uses: actions/checkout@v6
              with:
                  repository: aiidalab/aiidalab-registry
                  ref: main
                  path: aiidalab-registry

            - name: Build AiiDAlab registry
              run: cd aiidalab-registry && ./build.sh

    pre-commit:

        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:

            - uses: actions/checkout@v6

            - name: Set up uv
              uses: astral-sh/setup-uv@v7
              with:
                  python-version: '3.12'
                  activate-environment: true

            - name: Install dependencies
              run: uv pip install -e .[dev,registry]

            - name: Run pre-commit
              run: pre-commit run --all-files || (git status --short; git diff; exit 1)
